packages:
  - "apps/*"
  - "packages/*"
  - "workers/*"
onlyBuiltDependencies:
  - esbuild
ignoredBuiltDependencies:
  - sharp
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
